name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: deps
      run: make build_deps

    - name: Lint
      run: make lint

    - name: Run tests
      run: make test

    - name: Build amd64
      run: make amd64

    - name: Build arm32
      run: make arm
